#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-cookiejar
Version  : 0.3.3
Release  : 3
URL      : https://rubygems.org/downloads/cookiejar-0.3.3.gem
Source0  : https://rubygems.org/downloads/cookiejar-0.3.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
BuildRequires : ruby
BuildRequires : rubygem-bundler
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-rubygems-tasks

%description
Ruby CookieJar
==============
**Git**:	[http://github.com/dwaite/cookiejar](http://github.com/dwaite/cookiejar)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n cookiejar-0.3.3
gem spec %{SOURCE0} -l --ruby > rubygem-cookiejar.gemspec

%build
gem build rubygem-cookiejar.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
cookiejar-0.3.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/cookiejar-0.3.3
rspec -I.:lib spec/ || :
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/cookiejar-0.3.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/cdesc-Cookie.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/comment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/comment_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/compute_search_domains-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/created_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/decoded_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/discard-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/domain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/expired%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/expires_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/from_set_cookie-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/from_set_cookie2-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/http_only-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/ports-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/secure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/session%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/should_send%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Cookie/version-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/PATTERN/cdesc-PATTERN.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/cdesc-CookieValidation.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/compute_search_domains-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/compute_search_domains_for_host-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/cookie_base_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/decode_value-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/determine_cookie_domain-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/determine_cookie_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/domains_match-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/effective_host-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/hostname_reach-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/parse_set_cookie-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/parse_set_cookie2-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/to_domain-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/to_path-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/to_uri-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/validate_cookie-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/CookieValidation/value_to_string-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/InvalidCookieError/cdesc-InvalidCookieError.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/InvalidCookieError/messages-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/InvalidCookieError/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/add_cookie-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/add_cookie_to_path-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/cdesc-Jar.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/expire_cookies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/find_domain-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/find_or_add_domain_for_cookie-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/from_a-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/gather_header_values-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/get_cookie_header-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/get_cookies-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/set_cookie-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/set_cookie2-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/set_cookies_from_headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/to_a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/Jar/to_uri-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/CookieJar/cdesc-CookieJar.ri
/usr/lib64/ruby/gems/2.2.0/doc/cookiejar-0.3.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/README.markdown
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/contributors.json
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/cookiejar.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/lib/cookiejar.rb
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/lib/cookiejar/cookie.rb
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/lib/cookiejar/cookie_validation.rb
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/lib/cookiejar/jar.rb
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/lib/cookiejar/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/spec/cookie_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/spec/cookie_validation_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/spec/jar_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/cookiejar-0.3.3/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/cookiejar-0.3.3.gemspec
